# Aim 1 Team A 
## making the phyloseq 
```{r}
library(phyloseq)
library(tidyverse)
library(vegan)
library(dplyr)
library(ggplot2)
library(picante)
```


```{r}
taxonomy <- read.delim("taxonomy.tsv", row.names = 1)
tree <- read_tree("tree.nwk")
counts <- read.delim("feature-table.tsv", skip = 1, row.names = 1)
metadata <- read.delim("new_metadata.tsv", row.names = 1)


taxonomy_formatted = taxonomy %>% 
  separate(col = Taxon, 
           into = c('Domain','Phylum','Class','Order',
                    'Family','Genus','Species'),
           sep=';', fill='right') %>% 
  select(-Confidence) %>% 
  as.matrix()

counts_formatted = counts %>% as.matrix()
colnames(counts_formatted) <- sub("^X", "", colnames(counts_formatted))
colnames(counts_formatted) <- gsub("\\.", "-", colnames(counts_formatted))


meta_data <- read.delim(
  "new_metadata.tsv",
  sep = "\t",
  header = TRUE,
  row.names = 1,
  check.names = FALSE,
  comment.char = ""
)
meta_data <- meta_data[colnames(counts_formatted), ]


ps <- phyloseq(
  sample_data(meta_data),
  otu_table(counts_formatted, taxa_are_rows = TRUE),
  tax_table(taxonomy_formatted),
  tree
)

saveRDS(ps,'phyloseq_taxonomy.rds')
```


